In [1]:
import matplotlib.pyplot as plt
import numpy as np
from math import pi

In [2]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, transpile
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity 
from qiskit import BasicAer
backend = BasicAer.get_backend('unitary_simulator')

In [4]:
q = QuantumRegister (1)

In [5]:
qc = QuantumCircuit (q)
qc.u(pi/2,pi/4,pi/8,q)
qc.draw()

┌────────────────┐
q0: ┤ U(π/2,π/4,π/8) ├
    └────────────────┘

In [6]:
job = backend.run(transpile(qc, backend))
job.result ().get_unitary(qc, decimals=3)

array([[ 0.707+0.j   , -0.653-0.271j],
       [ 0.5  +0.5j  ,  0.271+0.653j]])

In [7]:
qc = QuantumCircuit(q)
qc.p(pi/2,q)
qc.draw()

┌────────┐
q0: ┤ P(π/2) ├
    └────────┘

In [8]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [9]:
qc = QuantumCircuit(q)
qc.id(q)
qc.draw()

┌───┐
q0: ┤ I ├
    └───┘

In [10]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [12]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

AttributeError: 'BasicAerJob' object has no attribute 'name'

In [13]:
qc = QuantumCircuit(q)
qc.y(q)
qc.draw()

┌───┐
q0: ┤ Y ├
    └───┘

In [14]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.+0.j, -0.-1.j],
       [ 0.+1.j,  0.+0.j]])

In [15]:
qc = QuantumCircuit(q)
qc.z(q)
qc.draw()

┌───┐
q0: ┤ Z ├
    └───┘

In [16]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [17]:
qc = QuantumCircuit(q)
qc.h(q)
qc.draw()

┌───┐
q0: ┤ H ├
    └───┘

In [18]:
import qiskit.tools.jupyter
%qiskit_version_table
%qiskit_copyright